server:
  port: 8888

logging:
  file:
    path: logs.mylog.log

Spring:
  application:
    name: myTest
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.107:3306/course?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456

mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/*